<section class="title-bar section-global-nav">
	<div class="row">
		<div class="button-container" data-responsive-toggle="example-menu" data-hide-for="medium">
			<button class="menu-icon dark" type="button" data-toggle></button>
		</div>
		<nav class="global-nav column">
			<a href="/" class="nav-item">DANA LEONG</a>
			<a href="/one-eyed-orange/" class="nav-item">ONE EYED ORANGE</a>
			<a href="/tektonik/" class="nav-item">TEKTONIK</a>
			<a href="/dl-trio/" class="nav-item">DL TRIO</a>
			<a href="/contact/" class="nav-item">CONTACT</a>
		</nav>
		<div id="global-nav-viewport-emitter" class="global-nav-viewport-emitter"></div>
	</div>
</section>

<main class="page page-<!--#echo var='PAGE_NAME'-->">