<section class="row upcoming-events">
	<div id="orbit" class="orbit columns" role="region" aria-label="Favorite Space Pictures" data-auto-play="false" data-infinite-wrap="false">
		<button class="orbit-previous" aria-label="previous"><span class="show-for-sr">Previous Slide</span>&#9664;</button>
		<button class="orbit-next" aria-label="next"><span class="show-for-sr">Next Slide</span>&#9654;</button>
		<ul class="orbit-container">
			<li class="is-active orbit-slide">
				<div class="board">
					<div class="tiles">

						<div class="tile">
							<div class="tile-content calendar">
								<span class="month">MARCH</span>
								<span class="day">11<sup>TH</sup></span>
								<span class="year">2016</span>
							</div>
							<div class="tile-content location">
								<span class="time">9:00PM</span>
								<span class="title">Denver Pavillion<br />Modern rming Arts School or Art</span>
								<span class="city-state">Denver, WI</span>
							</div>
						</div> <!-- / tile -->

						<div class="tile">
							<div class="tile-content calendar">
								<span class="month">SEPTEMBER</span>
								<span class="day">22<sup>ND</sup></span>
								<span class="year">2016</span>
							</div>
							<div class="tile-content location">
								<span class="time">9:00PM</span>
								<span class="title">Mishowaka<br />Performing Arts rming Arts Center</span>
								<span class="city-state">Italy, WI</span>
							</div>
						</div> <!-- / tile -->

						<div class="tile">
							<div class="tile-content calendar">
								<span class="month">SEPTEMBER</span>
								<span class="day">14<sup>TH</sup></span>
								<span class="year">2016</span>
							</div>
							<div class="tile-content location">
								<span class="time">9:00PM</span>
								<span class="title">South Milwaukee<br />Performinrming Arts rming Arts rming Arts g Arts Center</span>
								<span class="city-state">South Milwaukee, WI</span>
							</div>
						</div> <!-- / tile -->

						<div class="tile">
							<div class="tile-content calendar">
								<span class="month">SEPTEMBER</span>
								<span class="day">14<sup>TH</sup></span>
								<span class="year">2016</span>
							</div>
							<div class="tile-content location">
								<span class="time">9:00PM</span>
								<span class="title">South Milwaukee<br />Performrming Arts rming Arts ing Arts Center</span>
								<span class="city-state">South Milwaukee, WI</span>
							</div>
						</div> <!-- / tile -->

					</div>
				</div>
			</li>

			<li class="is-active orbit-slide">
				<div class="board">
					<div class="tiles">

						<div class="tile">
							<div class="tile-content calendar">
								<span class="month">SEPTEMBER</span>
								<span class="day">14<sup>TH</sup></span>
								<span class="year">2016</span>
							</div>
							<div class="tile-content location">
								<span class="time">9:00PM</span>
								<span class="title">South Milwaukee<br />Performing Arts Center</span>
								<span class="city-state">South Milwaukee, WI</span>
							</div>
						</div> <!-- / tile -->

						<div class="tile">
							<div class="tile-content calendar">
								<span class="month">SEPTEMBER</span>
								<span class="day">14<sup>TH</sup></span>
								<span class="year">2016</span>
							</div>
							<div class="tile-content location">
								<span class="time">9:00PM</span>
								<span class="title">South Milwaukee<br />Performrming Arts ing Arts Center</span>
								<span class="city-state">South Milwaukee, WI</span>
							</div>
						</div> <!-- / tile -->

						<div class="tile">
							<div class="tile-content calendar">
								<span class="month">SEPTEMBER</span>
								<span class="day">14<sup>TH</sup></span>
								<span class="year">2016</span>
							</div>
							<div class="tile-content location">
								<span class="time">9:00PM</span>
								<span class="title">South Milwaukee<br />Performing Arts Center</span>
								<span class="city-state">South Milwaukee, WI</span>
							</div>
						</div> <!-- / tile -->

						<div class="tile">
							<div class="tile-content calendar">
								<span class="month">SEPTEMBER</span>
								<span class="day">14<sup>TH</sup></span>
								<span class="year">2016</span>
							</div>
							<div class="tile-content location">
								<span class="time">9:00PM</span>
								<span class="title">South Milwaukee Performrming Arts rming <br />Performrming Arts rming Arts rming Arts ing Arts Center</span>
								<span class="city-state">South Milwaukee, WI</span>
							</div>
						</div> <!-- / tile -->

					</div>
				</div>

			</li>

		</ul>
		<!--<nav class="orbit-bullets">-->
			<!--<button class="is-active" data-slide="0"><span class="show-for-sr">First slide details.</span><span class="show-for-sr">Current Slide</span></button>-->
			<!--<button data-slide="1"><span class="show-for-sr">Second slide details.</span></button>-->
		<!--</nav>-->
	</div>
</section>